export const ADMIN_lOGIN_REQUEST = "ADMIN_LOGIN_REQUEST";
export const ADMIN_lOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS";
export const ADMIN_lOGIN_FAIL = "ADMIN_LOGIN_FAIL";
export const ADMIN_lOGOUT = "ADMIN_LOGOUT";

export const ADMIN_REGISTER_REQUEST = "ADMIN_REGISTER_REQUEST";
export const ADMIN_REGISTER_SUCCESS = "ADMIN_REGISTER_SUCCESS";
export const ADMIN_REGISTER_FAIL = "ADMIN_REGISTER_FAIL";